# Generated by Django 5.0.2 on 2024-02-23 02:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(auto_now=True)),
                ('Invoice', models.TextField(max_length=50, null=True)),
                ('CustomerName', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=50)),
                ('quantity', models.IntegerField(null=True)),
                ('unit_price', models.DecimalField(decimal_places=10, max_digits=19)),
                ('price', models.IntegerField(null=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='detail.invoice')),
            ],
        ),
    ]
